import Head from "next/head";
import { Home } from "components/home";

import type { NextPage } from "next";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Metroid Dread Leaderboard</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Home />
    </>
  );
};

export default HomePage;
